"""сделал gin инверсивный поиск в модели Product для настройи поиска по ключевым словам

Revision ID: 2f4da8fb6f71
Revises: 2a2880592ba0
Create Date: 2026-03-02 22:51:50.625910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f4da8fb6f71'
down_revision: Union[str, Sequence[str], None] = '2a2880592ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("\n            setweight(to_tsvector('russian', coalesce(name, '')), 'A') ||\n            setweight(to_tsvector('english', coalesce(name, '')), 'A') ||\n            setweight(to_tsvector('russian', coalesce(description, '')), 'B') ||\n            setweight(to_tsvector('english', coalesce(description, '')), 'B')\n                    ", persisted=True), nullable=False))
    op.drop_index(op.f('idx_products_category'), table_name='products')
    op.drop_index(op.f('idx_products_seller'), table_name='products')
    op.create_index('ix_products_tsv_gin', 'products', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_tsv_gin', table_name='products', postgresql_using='gin')
    op.create_index(op.f('idx_products_seller'), 'products', ['seller_id'], unique=False)
    op.create_index(op.f('idx_products_category'), 'products', ['category_id'], unique=False)
    op.drop_column('products', 'tsv')
    # ### end Alembic commands ###
