"""Добавил внешний ключ для OrderModel к UserModel

Revision ID: 52e17884e2cb
Revises: caa7d1bfd901
Create Date: 2026-03-05 17:57:38.561114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52e17884e2cb'
down_revision: Union[str, Sequence[str], None] = 'caa7d1bfd901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('order_items', 'updated_at')
    op.drop_column('order_items', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('order_items', 'quantity')
    # ### end Alembic commands ###
