"""Изменил модель OrderModel добавив поля для paid_at | payment_id

Revision ID: a6257ddde816
Revises: 52e17884e2cb
Create Date: 2026-03-06 21:18:28.212022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6257ddde816'
down_revision: Union[str, Sequence[str], None] = '52e17884e2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_id', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'orders', ['payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'payment_id')
    # ### end Alembic commands ###
