name: fastapi-ecommerce-prod
services:
  web:
    # Берем Dockerfile из каталога app
    build:
      context: .
      dockerfile: dockerfile.prod
    # Запускаем сервер Gunicorn
    command: gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    # Открываем порт 8000 внутри и снаружи
    # ports:
    #   - 8000:8000 # при nginx его надо закрыть, тк nginx сам все принимать будет
    depends_on: # сначала запускаем БД
      - db

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=ecommerce_store
  
  nginx:
    build: nginx # в папке nginx есть отдельный dockerfile
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  